# Generated by Django 6.0 on 2025-12-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('dish', 'Dish'), ('resturent', 'Resturent')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
