# Generated by Django 6.0 on 2025-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_rating_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_type',
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
