# Generated by Django 6.0 on 2025-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_rating_type_alter_rating_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.CharField(choices=[('dish', 'Dish'), ('resturent', 'Resturent')], max_length=10, null=True),
        ),
    ]
