# Generated by Django 6.0 on 2025-12-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_rating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='type',
            field=models.CharField(choices=[('dish', 'Dish'), ('restaurant', 'Restaurant')], max_length=10, null=True),
        ),
    ]
