
POST http://127.0.0.1:8000/api/v1/restaurants/
Content-Type:application/json
Cookie: sessionid=zul1pyqzu9hramberbok42do4ixqb15i

{
    "name":"myRest",
    "email":"rest2m@gmail.com",
    "phone":"1234667"
}

# PUT http://127.0.0.1:8000/api/v1/restaurants/8/
# Content-Type:application/json

# {
#     "name":"burger",
#     "email":"abrar@gmail.com",
#     "phone":"12345667"
# }

# DELETE  http://127.0.0.1:8000/api/v1/restaurant/16/
# Content-Type: application/json
# Cookie: sessionid=zul1pyqzu9hramberbok42do4ixqb15i



