# Generated by Django 6.0 on 2025-12-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='dish-img/'),
        ),
    ]
