# Generated by Django 6.0 on 2025-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dish_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='registed_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
